# Generated by Django 5.1.3 on 2024-11-09 10:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_direction', models.CharField(max_length=50)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_reports', to='news.place')),
            ],
        ),
    ]
